[package]
name = "util"
version = "0.1.0"
edition = "2021"

[dependencies]
Inflector = "0.11.4"
cmake-parser = "0.1.0-beta.1"
git2 = "0.20.0"
indoc = "2.0.5"
lazy_static = "1.5.0"
octocrab = "0.43.0"
toml = "0.8.20"
walkdir = "2.5.0"

[dependencies.clap]
version = "4.5.29"
features = ["derive"]

[dependencies.serde]
version = "1.0.217"
features = ["derive"]
